//Generated by AntilatencyApiGenerator
#pragma warning disable IDE1006 // Do not warn about naming style violations
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class AndroidJniWrapper : Scope {
		public static IElement _NameRef => new Deferred(()=>Material).Modify().ContentReplace($"AndroidJniWrapper").AddClasses("Namespace");
		public static IElement NameRefCode => _NameRef.Modify().Wrap("code");
		public static IElement _FullNameRef => _NameRef;
		public static IElement FullNameRefCode => _FullNameRef.Modify().Wrap("code");
		public static Material Material => new Material("AndroidJniWrapper",null,$"Top-level namespace. See {Api.Material} for a complete list of top-level namespaces")
			[new Section("Types")
				[new UnorderedList()
					[$"*interface* {IAndroidJni.NameRefCode}"]
				]
			]
			;
		public sealed partial class IAndroidJni : Scope {
			public static IElement _NameRef => new Deferred(()=>Material).Modify().ContentReplace($"IAndroidJni").AddClasses("Type");
			public static IElement NameRefCode => _NameRef.Modify().Wrap("code");
			public static IElement _FullNameRef => new Text($"{AndroidJniWrapper._FullNameRef}.{_NameRef}");
			public static IElement FullNameRefCode => _FullNameRef.Modify().Wrap("code");
			public static IElement RawDeclarationCode => new Text($"{Interface} {_NameRef} : {Namespace("ntilatency.InterfaceContract")}.{Type("IInterface")} {{\n    {Methods.initJni.RawDeclarationCode};\n}}");
			public static IElement CodeBlock => CodeBlock(RawDeclarationCode);
			public static Material Material => new Material("AndroidJniWrapper.IAndroidJni",null,$"Interface in `{Api.AndroidJniWrapper._FullNameRef}`")[CodeBlock];
			public sealed partial class Methods : Scope {
				public sealed partial class initJni : Scope {
					public static IElement _NameRef => new Deferred(()=>Material).Modify().ContentReplace($"initJni").AddClasses("Method");
					public static IElement NameRefCode => _NameRef.Modify().Wrap("code");
					public static IElement _FullNameRef => new Text($"{IAndroidJni._FullNameRef}.{_NameRef}");
					public static IElement FullNameRefCode => _FullNameRef.Modify().Wrap("code");
					public static IElement CodeBlock => CodeBlock(RawDeclarationCode);
					public static IElement CodeInline => CodeInline(RawDeclarationCode);
					public static IElement RawDeclarationCode => new Text($"{Keyword("void")} {_NameRef}({Parameters.vm.RawDeclarationCode}, {Parameters.context.RawDeclarationCode})");
					public static Material Material => new Material("AndroidJniWrapper.IAndroidJni.initJni",null,$"Method of `{Api.AndroidJniWrapper.IAndroidJni._NameRef}`\n`{RawDeclarationCode}`")
						[new Section("Parameters")]
						;
					public sealed partial class Parameters : Scope {
						public sealed partial class vm : Scope {
							public static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							public static IElement CodeInline => CodeInline(RawDeclarationCode);
							public static IElement RawDeclarationCode => new Text($"{Keyword("pointer")} {_Name}");
							public static IElement _Name => new Modify($"vm").Attribute("title", "parameter vm");
							public static IElement NameCode => _Name.Modify().Wrap("code");
						} //scope vm
						public sealed partial class context : Scope {
							public static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							public static IElement CodeInline => CodeInline(RawDeclarationCode);
							public static IElement RawDeclarationCode => new Text($"{Keyword("pointer")} {_Name}");
							public static IElement _Name => new Modify($"context").Attribute("title", "parameter context");
							public static IElement NameCode => _Name.Modify().Wrap("code");
						} //scope context
					} //scope Parameters
				} //scope initJni
			} //scope Methods
		} //scope IAndroidJni
		
		
	} //scope AndroidJniWrapper
} //scope Api
