//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Tasks : Scope {
				public sealed partial class Tests : Scope {
					public sealed partial class Reset : Scope {
						public static IElement NameRef => new Deferred(()=>Material).Modify().ContentReplace($"Reset");
						public static IElement FullNameRef => new Deferred(()=>Material);
						public static Material Material => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Reset",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.FullNameRef}`")[new Section("Types")
							[new UnorderedList()
								[$"*constant group* `{Constants.NameRef}`"]
								[$"*interface* `{IHostToDevice.NameRef}`"]
								[$"*interface* `{IDeviceToHost.NameRef}`"]
							]
						];
						public sealed partial class Constants : Scope {
							public static IElement NameRef => new Deferred(()=>Material).Modify().ContentReplace($"Constants");
							public static IElement FullNameRef => new Deferred(()=>Material);
							public static Material Material => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Reset\u200B.Constants",null,$"Constants in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.Reset.FullNameRef}`");
						} //scope Constants
						
						public sealed partial class IHostToDevice : Scope {
							public static IElement NameRef => new Deferred(()=>Material).Modify().ContentReplace($"IHostToDevice");
							public static IElement FullNameRef => new Deferred(()=>Material);
							public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : InterfaceContract.{Type("IInterface")} {{\n}}");
							public static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							public static Material Material => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Reset\u200B.IHostToDevice",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.Reset.FullNameRef}`")[CodeBlock];
							public sealed partial class Methods : Scope {
							} //scope Methods
						} //scope IHostToDevice
						
						public sealed partial class IDeviceToHost : Scope {
							public static IElement NameRef => new Deferred(()=>Material).Modify().ContentReplace($"IDeviceToHost");
							public static IElement FullNameRef => new Deferred(()=>Material);
							public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : InterfaceContract.{Type("IInterface")} {{\n}}");
							public static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							public static Material Material => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Reset\u200B.IDeviceToHost",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.Reset.FullNameRef}`")[CodeBlock];
							public sealed partial class Methods : Scope {
							} //scope Methods
						} //scope IDeviceToHost
						
						
					} //scope Reset
				} //scope Tests
			} //scope Tasks
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
