//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Property : Scope {
				public static IElement NameRef => new ContentReplace(FullNameRef, $"Property");
				public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Property");
				private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Property",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.FullNameRef}`")[new Section("Types")
					[new UnorderedList()
						[$"*enum* `{AccessLevel.NameRef}`"]
						[$"*struct* `{KeyString.NameRef}`"]
					]
				];
				public sealed partial class AccessLevel : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"AccessLevel");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Property.AccessLevel");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Property\u200B.AccessLevel",null,$"Enum in `{Api.Antilatency.DeviceNetwork.Property.FullNameRef}`");
				} //scope AccessLevel
				
				public sealed partial class KeyString : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"KeyString");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Property.KeyString");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Property\u200B.KeyString",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Property.FullNameRef}`");
				} //scope KeyString
				
				
			} //scope Property
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
