//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Tasks : Scope {
				public static IElement NameRef => new ContentReplace(FullNameRef, $"Tasks");
				public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks");
				private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.FullNameRef}`")[new Section("Types")
					[new UnorderedList()
					]
				];
				
			} //scope Tasks
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
