//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Interop : Scope {
				public static IElement NameRef => new ContentReplace(FullNameRef, $"Interop");
				public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop");
				private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.FullNameRef}`")[new Section("Types")
					[new UnorderedList()
						[$"*interface* `{IDataReceiver.NameRef}`"]
						[$"*struct* `{Packet.NameRef}`"]
						[$"*constant group* `{Constants.NameRef}`"]
						[$"*struct* `{String16.NameRef}`"]
						[$"*struct* `{WriteBufferOverflowException.NameRef}`"]
						[$"*struct* `{PacketDescription.NameRef}`"]
						[$"*interface* `{ITaskSignature.NameRef}`"]
						[$"*interface* `{IConnection.NameRef}`"]
					]
				];
				public sealed partial class Packet : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"Packet");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Packet");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Packet",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`");
				} //scope Packet
				
				public sealed partial class IDataReceiver : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"IDataReceiver");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.IDataReceiver");
					public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : {Type("Antilatency.InterfaceContract.IInterface")} {{\n    {packet.RawDeclarationCode}\n}}");
					private static IElement CodeBlock => CodeBlock(RawDeclarationCode);
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.IDataReceiver",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`")[CodeBlock];
					/// <summary>Write packet to data receiver</summary>
					/// <param name = "packet">
					/// Packet with data
					/// </param>
					public sealed partial class packet : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"packet");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.IDataReceiver.packet");
						public static IElement RawDeclarationCode => new Text($"{Type("void")} {NameRef}({Parameters.packet.RawDeclarationCode})");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.IDataReceiver\u200B.packet",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Interop.IDataReceiver.FullNameRef)}`\n`{Type("void")} {NameRef}({Parameters.packet.RawDeclarationCode})`")
							[new Section("Parameters")]
							;
						public sealed partial class Parameters : Scope {
							public sealed partial class packet : Scope {
								public static IElement RawDeclarationCode => new Text($"{Type(Api.Antilatency.DeviceNetwork.Interop.Packet.FullNameRef)} {Name}");public static IElement Name => new Modify($"packet").SetAttributeValue("title", "parameter packet");
							} //scope packet
						} //scope Parameters
					} //scope packet
				} //scope IDataReceiver
				
				public sealed partial class Constants : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"Constants");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Constants");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Constants",null,$"Constants in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`");
				} //scope Constants
				
				public sealed partial class String16 : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"String16");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.String16");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.String16",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`");
				} //scope String16
				
				public sealed partial class WriteBufferOverflowException : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"WriteBufferOverflowException");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.WriteBufferOverflowException");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.WriteBufferOverflowException",null,$"Exception in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`");
				} //scope WriteBufferOverflowException
				
				public sealed partial class PacketDescription : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"PacketDescription");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.PacketDescription");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.PacketDescription",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`");
				} //scope PacketDescription
				
				public sealed partial class ITaskSignature : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"ITaskSignature");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.ITaskSignature");
					public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : {Type("Antilatency.InterfaceContract.IInterface")} {{\n    {getGuid.RawDeclarationCode}\n    {getWritePacketDescription.RawDeclarationCode}\n    {getReadPacketDescription.RawDeclarationCode}\n}}");
					private static IElement CodeBlock => CodeBlock(RawDeclarationCode);
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.ITaskSignature",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`")[CodeBlock];
					public sealed partial class getGuid : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"getGuid");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.ITaskSignature.getGuid");
						public static IElement RawDeclarationCode => new Text($"{Type("Guid")} {NameRef}()");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.ITaskSignature\u200B.getGuid",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Interop.ITaskSignature.FullNameRef)}`\n`{Type("Guid")} {NameRef}()`")
							[new Section("Parameters")]
							;
						public sealed partial class Parameters : Scope {
						} //scope Parameters
					} //scope getGuid
					public sealed partial class getWritePacketDescription : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"getWritePacketDescription");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.ITaskSignature.getWritePacketDescription");
						public static IElement RawDeclarationCode => new Text($"{Type("bool")} {NameRef}({Parameters.index.RawDeclarationCode}, {Parameters.description.RawDeclarationCode})");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.ITaskSignature\u200B.getWritePacketDescription",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Interop.ITaskSignature.FullNameRef)}`\n`{Type("bool")} {NameRef}({Parameters.index.RawDeclarationCode}, {Parameters.description.RawDeclarationCode})`")
							[new Section("Parameters")]
							;
						public sealed partial class Parameters : Scope {
							public sealed partial class index : Scope {
								public static IElement RawDeclarationCode => new Text($"{Type("uint")} {Name}");public static IElement Name => new Modify($"index").SetAttributeValue("title", "parameter index");
							} //scope index
							public sealed partial class description : Scope {
								public static IElement RawDeclarationCode => new Text($"{Type(Api.Antilatency.DeviceNetwork.Interop.PacketDescription.FullNameRef)} {Name}");public static IElement Name => new Modify($"description").SetAttributeValue("title", "parameter description");
							} //scope description
						} //scope Parameters
					} //scope getWritePacketDescription
					public sealed partial class getReadPacketDescription : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"getReadPacketDescription");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.ITaskSignature.getReadPacketDescription");
						public static IElement RawDeclarationCode => new Text($"{Type("bool")} {NameRef}({Parameters.index.RawDeclarationCode}, {Parameters.description.RawDeclarationCode})");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.ITaskSignature\u200B.getReadPacketDescription",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Interop.ITaskSignature.FullNameRef)}`\n`{Type("bool")} {NameRef}({Parameters.index.RawDeclarationCode}, {Parameters.description.RawDeclarationCode})`")
							[new Section("Parameters")]
							;
						public sealed partial class Parameters : Scope {
							public sealed partial class index : Scope {
								public static IElement RawDeclarationCode => new Text($"{Type("uint")} {Name}");public static IElement Name => new Modify($"index").SetAttributeValue("title", "parameter index");
							} //scope index
							public sealed partial class description : Scope {
								public static IElement RawDeclarationCode => new Text($"{Type(Api.Antilatency.DeviceNetwork.Interop.PacketDescription.FullNameRef)} {Name}");public static IElement Name => new Modify($"description").SetAttributeValue("title", "parameter description");
							} //scope description
						} //scope Parameters
					} //scope getReadPacketDescription
				} //scope ITaskSignature
				
				public sealed partial class IConnection : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"IConnection");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.IConnection");
					public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : {Type(Api.Antilatency.DeviceNetwork.Interop.IDataReceiver.FullNameRef)} {{\n    {setDataReceiver.RawDeclarationCode}\n}}");
					private static IElement CodeBlock => CodeBlock(RawDeclarationCode);
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.IConnection",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`")[CodeBlock];
					public sealed partial class setDataReceiver : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"setDataReceiver");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.IConnection.setDataReceiver");
						public static IElement RawDeclarationCode => new Text($"{Type("void")} {NameRef}({Parameters.dataReceiver.RawDeclarationCode})");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.IConnection\u200B.setDataReceiver",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Interop.IConnection.FullNameRef)}`\n`{Type("void")} {NameRef}({Parameters.dataReceiver.RawDeclarationCode})`")
							[new Section("Parameters")]
							;
						public sealed partial class Parameters : Scope {
							public sealed partial class dataReceiver : Scope {
								public static IElement RawDeclarationCode => new Text($"{Type(Api.Antilatency.DeviceNetwork.Interop.IDataReceiver.FullNameRef)} {Name}");public static IElement Name => new Modify($"dataReceiver").SetAttributeValue("title", "parameter dataReceiver");
							} //scope dataReceiver
						} //scope Parameters
					} //scope setDataReceiver
				} //scope IConnection
				
				
			} //scope Interop
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
