//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public static IElement _FullNameRef => new Deferred(()=>Material).Modify().AddClasses("Namespace");
		public static IElement FullNameRefCode => _FullNameRef.Modify().Wrap("code");
		public static Material Material => new Material("Antilatency",null,$"Root namespace")[new Section("Types")
			[new UnorderedList()
			]
		];
		
	} //scope Antilatency
} //scope Api
