//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Tasks : Scope {
				public sealed partial class Tests : Scope {
					public sealed partial class Sync : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Sync");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.Sync");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Sync",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.FullNameRef}`")[new Section("Types")
							[new UnorderedList()
								[$"*constant group* `{Constants.NameRef}`"]
								[$"*interface* `{IHostToDevice.NameRef}`"]
								[$"*interface* `{IDeviceToHost.NameRef}`"]
							]
						];
						public sealed partial class Constants : Scope {
							public static IElement NameRef => new ContentReplace(FullNameRef, $"Constants");
							public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.Sync.Constants");
							private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Sync\u200B.Constants",null,$"Constants in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.Sync.FullNameRef}`");
						} //scope Constants
						
						public sealed partial class IHostToDevice : Scope {
							public static IElement NameRef => new ContentReplace(FullNameRef, $"IHostToDevice");
							public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.Sync.IHostToDevice");
							public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : {Type("Antilatency.InterfaceContract.IInterface")} {{\n    {ack.RawDeclarationCode}\n}}");
							private static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Sync\u200B.IHostToDevice",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.Sync.FullNameRef}`")[CodeBlock];
							public sealed partial class ack : Scope {
								public static IElement NameRef => new ContentReplace(FullNameRef, $"ack");
								public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.Sync.IHostToDevice.ack");
								public static IElement RawDeclarationCode => new Text($"{Type("void")} {NameRef}()");
								private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Sync\u200B.IHostToDevice\u200B.ack",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Tasks.Tests.Sync.IHostToDevice.FullNameRef)}`\n`{Type("void")} {NameRef}()`")
									[new Section("Parameters")]
									;
								public sealed partial class Parameters : Scope {
								} //scope Parameters
							} //scope ack
						} //scope IHostToDevice
						
						public sealed partial class IDeviceToHost : Scope {
							public static IElement NameRef => new ContentReplace(FullNameRef, $"IDeviceToHost");
							public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.Sync.IDeviceToHost");
							public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : {Type("Antilatency.InterfaceContract.IInterface")} {{\n    {ack.RawDeclarationCode}\n}}");
							private static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Sync\u200B.IDeviceToHost",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.Sync.FullNameRef}`")[CodeBlock];
							public sealed partial class ack : Scope {
								public static IElement NameRef => new ContentReplace(FullNameRef, $"ack");
								public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.Sync.IDeviceToHost.ack");
								public static IElement RawDeclarationCode => new Text($"{Type("void")} {NameRef}()");
								private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.Sync\u200B.IDeviceToHost\u200B.ack",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Tasks.Tests.Sync.IDeviceToHost.FullNameRef)}`\n`{Type("void")} {NameRef}()`")
									[new Section("Parameters")]
									;
								public sealed partial class Parameters : Scope {
								} //scope Parameters
							} //scope ack
						} //scope IDeviceToHost
						
						
					} //scope Sync
				} //scope Tests
			} //scope Tasks
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
