//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Tasks : Scope {
				public sealed partial class Default : Scope {
					public static IElement NameRef => new Deferred(()=>Material).Modify().ContentReplace($"Default");
					public static IElement FullNameRef => new Deferred(()=>Material);
					public static Material Material => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Default",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.Tasks.FullNameRef}`")[new Section("Types")
						[new UnorderedList()
						]
					];
					
				} //scope Default
			} //scope Tasks
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
