//Generated by AntilatencyApiGenerator
#pragma warning disable IDE1006 // Do not warn about naming style violations
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Tasks : Scope {
				public sealed partial class Default : Scope {
					public static IElement _NameRef => new Deferred(()=>Material).Modify().ContentReplace($"Default").AddClasses("Namespace");
					public static IElement NameRefCode => _NameRef.Modify().Wrap("code");
					public static IElement _FullNameRef => new Text($"{Antilatency.DeviceNetwork.Tasks._FullNameRef}.{_NameRef}");
					public static IElement FullNameRefCode => _FullNameRef.Modify().Wrap("code");
					public static Material Material => new Material("Antilatency.DeviceNetwork.Tasks.Default",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.Tasks._FullNameRef}`")
						[new Section("Nested Namespaces")
							[new UnorderedList()
								[Api.Antilatency.DeviceNetwork.Tasks.Default.PropertyManager.NameRefCode]
								[Api.Antilatency.DeviceNetwork.Tasks.Default.Idle.NameRefCode]
							]
						]
						;
					
				} //scope Default
			} //scope Tasks
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
