//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Tasks : Scope {
				public sealed partial class Tests : Scope {
					public sealed partial class SoftReset : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"SoftReset");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.SoftReset");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.SoftReset",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.FullNameRef}`")[new Section("Types")
							[new UnorderedList()
								[$"*constant group* `{Constants.NameRef}`"]
								[$"*interface* `{IHostToDevice.NameRef}`"]
								[$"*interface* `{IDeviceToHost.NameRef}`"]
							]
						];
						public sealed partial class Constants : Scope {
							public static IElement NameRef => new ContentReplace(FullNameRef, $"Constants");
							public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.Constants");
							private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.SoftReset\u200B.Constants",null,$"Constants in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.FullNameRef}`");
						} //scope Constants
						
						public sealed partial class IHostToDevice : Scope {
							public static IElement NameRef => new ContentReplace(FullNameRef, $"IHostToDevice");
							public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.IHostToDevice");
							public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : {Type("Antilatency.InterfaceContract.IInterface")} {{\n    {timeout.RawDeclarationCode}\n}}");
							private static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.SoftReset\u200B.IHostToDevice",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.FullNameRef}`")[CodeBlock];
							public sealed partial class timeout : Scope {
								public static IElement NameRef => new ContentReplace(FullNameRef, $"timeout");
								public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.IHostToDevice.timeout");
								public static IElement RawDeclarationCode => new Text($"{Type("void")} {NameRef}({Parameters.delay.RawDeclarationCode})");
								private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.SoftReset\u200B.IHostToDevice\u200B.timeout",null,$"Method of `{Type(Api.Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.IHostToDevice.FullNameRef)}`\n`{Type("void")} {NameRef}({Parameters.delay.RawDeclarationCode})`")
									[new Section("Parameters")]
									;
								public sealed partial class Parameters : Scope {
									public sealed partial class delay : Scope {
										public static IElement RawDeclarationCode => new Text($"{Type("uint")} {Name}");public static IElement Name => new Modify($"delay").SetAttributeValue("title", "parameter delay");
									} //scope delay
								} //scope Parameters
							} //scope timeout
						} //scope IHostToDevice
						
						public sealed partial class IDeviceToHost : Scope {
							public static IElement NameRef => new ContentReplace(FullNameRef, $"IDeviceToHost");
							public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.IDeviceToHost");
							public static IElement RawDeclarationCode => new Text($"{Interface} {NameRef} : {Type("Antilatency.InterfaceContract.IInterface")} {{\n}}");
							private static IElement CodeBlock => CodeBlock(RawDeclarationCode);
							private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Tasks\u200B.Tests\u200B.SoftReset\u200B.IDeviceToHost",null,$"Interface in `{Api.Antilatency.DeviceNetwork.Tasks.Tests.SoftReset.FullNameRef}`")[CodeBlock];
						} //scope IDeviceToHost
						
						
					} //scope SoftReset
				} //scope Tests
			} //scope Tasks
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
