//Generated by AntilatencyApiGenerator
using Csml;
public sealed partial class Api : Scope {
	public sealed partial class Antilatency : Scope {
		public sealed partial class DeviceNetwork : Scope {
			public sealed partial class Interop : Scope {
				public sealed partial class Memory : Scope {
					public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory");
					public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory");
					private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory",null,$"Namespace in `{Api.Antilatency.DeviceNetwork.Interop.FullNameRef}`")[new Section("Types")
						[new UnorderedList()
							[$"*struct* `{Memory2.NameRef}`"]
							[$"*struct* `{Memory4.NameRef}`"]
							[$"*struct* `{Memory8.NameRef}`"]
							[$"*struct* `{Memory16.NameRef}`"]
							[$"*struct* `{Memory32.NameRef}`"]
							[$"*struct* `{Memory64.NameRef}`"]
							[$"*struct* `{Memory128.NameRef}`"]
							[$"*struct* `{Memory255.NameRef}`"]
							[$"*struct* `{Memory62.NameRef}`"]
							[$"*struct* `{Memory63.NameRef}`"]
						]
					];
					public sealed partial class Memory2 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory2");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory2");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory2",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory2
					
					public sealed partial class Memory4 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory4");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory4");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory4",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory4
					
					public sealed partial class Memory8 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory8");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory8");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory8",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory8
					
					public sealed partial class Memory16 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory16");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory16");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory16",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory16
					
					public sealed partial class Memory32 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory32");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory32");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory32",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory32
					
					public sealed partial class Memory64 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory64");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory64");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory64",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory64
					
					public sealed partial class Memory128 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory128");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory128");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory128",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory128
					
					public sealed partial class Memory255 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory255");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory255");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory255",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory255
					
					public sealed partial class Memory62 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory62");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory62");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory62",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory62
					
					public sealed partial class Memory63 : Scope {
						public static IElement NameRef => new ContentReplace(FullNameRef, $"Memory63");
						public static MultiLanguageGroup FullNameRef => new MultiLanguageGroup("Antilatency.DeviceNetwork.Interop.Memory.Memory63");
						private static Material FullNameRef_en => new Material("Antilatency\u200B.DeviceNetwork\u200B.Interop\u200B.Memory\u200B.Memory63",null,$"Struct in `{Api.Antilatency.DeviceNetwork.Interop.Memory.FullNameRef}`");
					} //scope Memory63
					
					
				} //scope Memory
			} //scope Interop
		} //scope DeviceNetwork
	} //scope Antilatency
} //scope Api
