//Generated by AntilatencyApiGenerator
#pragma warning disable IDE1006 // Do not warn about naming style violations
using Csml;
using static ApiStatic;
public sealed partial class Api : Scope {
	public static Material Material => new Material("Api",null,$"")
		[new Section("Nested Namespaces")
			[new UnorderedList()
				[Api.AndroidJniWrapper.NameRefCode]
				[Api.Antilatency.NameRefCode]
			]
		]
		;
} //scope Api
